//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sesDeneme.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int commandId { get; set; }
        public string command1 { get; set; }
        public string response { get; set; }
        public string action { get; set; }
        public Nullable<bool> speak { get; set; }
    }
}
